TEAMS = [
    ['ARI', 'Arizona', 'Cardinals', 'Arizona Cardinals', 'At Arizona'],
    ['ATL', 'Atlanta', 'Falcons', 'Atlanta Falcons', 'At Atlanta'],
    ['BAL', 'Baltimore', 'Ravens', 'Baltimore Ravens', 'At Baltimore'],
    ['BUF', 'Buffalo', 'Bills', 'Buffalo Bills', 'At Buffalo'],
    ['CAR', 'Carolina', 'Panthers', 'Carolina Panthers', 'At Carolina'],
    ['CHI', 'Chicago', 'Bears', 'Chicago Bears', 'At Chicago'],
    ['CIN', 'Cincinnati', 'Bengals', 'Cincinnati Bengals','At Cincinnati'],
    ['CLE', 'Cleveland', 'Browns', 'Cleveland Browns', 'At Cleveland'],
    ['DAL', 'Dallas', 'Cowboys', 'Dallas Cowboys', 'At Dallas'],
    ['DEN', 'Denver', 'Broncos', 'Denver Broncos', 'At Denver'],
    ['DET', 'Detroit', 'Lions', 'Detroit Lions', 'At Detroit'],
    ['GB', 'Green Bay', 'Packers', 'Green Bay Packers', 'G.B.', 'GNB', 'At Green Bay'],
    ['HOU', 'Houston', 'Texans', 'Houston Texans', 'At Houston'],
    ['IND', 'Indianapolis', 'Colts', 'Indianapolis Colts', 'At Indianapolis'],
    ['JAC', 'Jacksonville', 'Jaguars', 'Jacksonville Jaguars', 'JAX', 'At Jacksonville'],
    ['KC', 'Kansas City', 'Chiefs', 'Kansas City Chiefs', 'K.C.', 'KAN', 'At Kansas City'],
    ['MIA', 'Miami', 'Dolphins', 'Miami Dolphins', 'At Miami'],
    ['MIN', 'Minnesota', 'Vikings', 'Minnesota Vikings', 'At Minnesota'],
    ['NE', 'New England', 'Patriots', 'New England Patriots', 'N.E.', 'NWE', 'At New England'],
    ['NO', 'New Orleans', 'Saints', 'New Orleans Saints', 'N.O.', 'NOR', 'At New Orleans'],
    ['NYG', 'Giants', 'New York Giants', 'N.Y.G.', 'At NY Giants', 'NY Giants'],
    ['NYJ', 'Jets', 'New York Jets', 'N.Y.J.', 'At NY Jets', 'NY Jets'],
    ['OAK', 'Oakland', 'Raiders', 'Oakland Raiders', 'At Oakland'],
    ['PHI', 'Philadelphia', 'Eagles', 'Philadelphia Eagles', 'At Philadelphia'],
    ['PIT', 'Pittsburgh', 'Steelers', 'Pittsburgh Steelers', 'At Pittsburgh'],
    ['SD', 'San Diego', 'Chargers', 'San Diego Chargers', 'S.D.', 'SDG', 'At San Diego'],
    ['SEA', 'Seattle', 'Seahawks', 'Seattle Seahawks', 'At Seattle'],
    ['SF', 'San Francisco', '49ers', 'San Francisco 49ers', 'S.F.', 'SFO', 'At San Francisco'],
    ['STL', 'St. Louis', 'Rams', 'St. Louis Rams', 'S.T.L.', 'At St. Louis'],
    ['TB', 'Tampa Bay', 'Buccaneers', 'Tampa Bay Buccaneers', 'T.B.', 'TAM', 'At Tampa Bay'],
    ['TEN', 'Tennessee', 'Titans', 'Tennessee Titans', 'At Tennessee'],
    ['WAS', 'Washington', 'Redskins', 'Washington Redskins', 'WSH', 'At Washington'],
    ['LA', 'Los Angeles', 'Rams', 'Los Angeles', 'Los Angeles']
]       

